# -----------------------------------------------------------------------
# Configuration file for https://travis-ci.org/elastic/elasticsearch-ruby
# -----------------------------------------------------------------------

dist: trusty

sudo: required

language: ruby

branches:
  only:
    - master
    - 6.x
    - 5.x

matrix:
  include:
    - rvm: ruby-head
      jdk: oraclejdk8
      env: TEST_SUITE=unit

    - rvm: 2.5.3
      jdk: oraclejdk8
      env: TEST_SUITE=unit

    - rvm: 2.2.10
      jdk: oraclejdk8
      env: TEST_SUITE=unit

    - rvm: jruby-9.2.0.0
      jdk: oraclejdk8
      env: TEST_SUITE=unit

    - rvm: 2.5.3
      jdk: oraclejdk8
      env: TEST_SUITE=integration SERVER=start TEST_CLUSTER_LOGS=/tmp/log TEST_BUILD_REF=origin/6.4 QUIET=true TEST_CLUSTER_COMMAND=/tmp/elasticsearch-6.4.2/bin/elasticsearch

allow_failures:
  - rvm: ruby-head
    jdk: oraclejdk8
    env: TEST_SUITE=unit

before_install:
  - gem update --system
  - gem --version
  - gem install bundler -v 1.14.3
  - bundle version
  - curl -sS https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.4.2.tar.gz | tar xz -C /tmp
  - rake setup
  - rake elasticsearch:update
  - /tmp/elasticsearch-6.4.2/bin/elasticsearch-keystore create

install:
  - bundle install
  - rake bundle:clean
  - rake bundle:install

script:
  - rake test:$TEST_SUITE

notifications:
  disable: true
